name: Maven Build with Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Adjust as necessary

jobs:
  build:
    runs-on: self-hosted  # Specifies the self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Runs the Maven build

      - name: Run tests
        run: mvn test  # Runs the Maven test
