name: Run Selenium Tests with Selenoid

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '30 2 * * *' # 8:00 AM IST

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Selenoid
        run: |
          # Pull the required browser images
          docker pull selenoid/chrome:latest
          docker pull selenoid/firefox:latest
          
          # Create a configuration directory and browsers.json
          mkdir -p $GITHUB_WORKSPACE/config
          echo '{
            "chrome": {
              "default": "latest",
              "versions": {
                "latest": {
                  "image": "selenoid/chrome:latest",
                  "port": "4444",
                  "path": "/"
                }
              }
            },
            "firefox": {
              "default": "latest",
              "versions": {
                "latest": {
                  "image": "selenoid/firefox:latest",
                  "port": "4444",
                  "path": "/"
                }
              }
            }
          }' > $GITHUB_WORKSPACE/config/browsers.json

          # Run Selenoid with the configuration
          docker run -d --name selenoid -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $GITHUB_WORKSPACE/config/browsers.json:/etc/selenoid/browsers.json \
            aerokube/selenoid:latest-release -conf /etc/selenoid/browsers.json

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
