name: Maven Build with Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Adjust as necessary

jobs:
  build:
    runs-on: self-hosted  # Specifies the self-hosted runner
    env:
      MAVEN_OPTS: "-Xmx1024m"  # Example environment variable for Maven
      JAVA_HOME: "/usr/lib/jvm/java-11-openjdk"  # Path to Java home (optional, usually set by setup-java)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specifies Java version
          distribution: 'adopt'  # Specifies the Java distribution

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip apt-transport-https ca-certificates curl software-properties-common
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          CHROME_DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome Installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Runs the Maven build

      - name: Run tests
        run: mvn test  # Runs the Maven tests
